from .add import parse_add
from .concat import parse_concat
from .avgpool import parse_avgpool
from .conv2d import parse_conv2d
from .gather import parse_gather
from .fc import parse_fc
from .maxpool import parse_maxpool
from .mean1dto2d import parse_mead1dto2d
from .SEelement import parse_SEelement
from .upsample import parse_upsample
from .sigmoid import parse_sigmoid
from .softmax import parse_softmax
from .tanh import parse_tanh
from .dequantize import parse_dequantize
from .quantize import parse_quantize
